### ISSUE TITLE
Consider moving tests outside of src/

### ISSUE THREAD

**Issue by Wojciechem** [michalbiarda/shipx-php-sdk#6]
A pretty standard practice for libraries is to have two directories at the root:
- src/
- tests/

and include tests only in autoload-dev.

This also allows to exclude tests from "dist" library, using .gitattributes with `tests/ export-ignore` - making it a bit more lightweight - great for production use.

**Comment by michalbiarda** [comment]
@Wojciechem Thanks for creating first issue in my repo :-). Your suggestion sounds legit. Could you please confirm that you're talking about something like that: https://madewithlove.com/blog/software-engineering/gitattributes/ ?

**Comment by michalbiarda** [comment]
@Wojciechem I am not an expert on .gitattributes. Could you please review my PR or tell how to properly test this change?

**Comment by Wojciechem** [comment]
@michalbiarda Yes, the article summarizes it well.
I'm no expert either, literally used .gitattributes once, just for this use-case :) but yours looks fine.
Github will generate zip archive - "release" for tag, the export-ignored files should not be present - that's it :)

**Comment by michalbiarda** [comment]
Thanks @Wojciechem :+1:. I merged it at it worked just fine :-).
